[package]
name = "seed-playground"
version = "0.1.0"
authors = ["pierrick.bouvier@posteo.net"]
edition = "2018"

[dependencies]
seed = "0.8.0"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "CanvasRenderingContext2d", "ImageData"
]
